# -*- coding: utf-8 -*-
"""KELOMPOK 1_project_python_part1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eFc4J2s6xLo0aTTl6Co4gbEtNFunmlej

# Soal 1

> Menentukan Bilangan Ganjil dan Genap.

Buatlah sebuah program yang meminta pengguna untuk memasukkan sebuah angka. Program tersebut kemudian harus menentukan apakah angka tersebut adalah bilangan ganjil atau genap
"""

n = int(input('masukan angka: '))
if n%2 == 0: #ciri-ciri bilangan genap adalah habis dibagi 2
  print("adalah bilangan genap")
else:
  print("adalah bilangan ganjil")

"""# Soal 2

> Menentukan Kelulusan Siswa

Buatlah sebuah program yang mengevaluasi nilai siswa. Jika nilai siswa 70 atau lebih, siswa tersebut lulus. Jika tidak, siswa tersebut tidak lulus. Program harus mengeluarkan pesan yang sesuai berdasarkan nilai siswa.


"""

nilai = float(input('nilai siswa:'))

if nilai >= 70: #kondisi
  print("selamat siswa lulus") #statement
else: #kondisi jika diatas salah
  print("maaf siswa tidak lulus")

"""# Soal 3

> Menentukan Rentang Nilai

Buatlah sebuah program yang meminta pengguna untuk memasukkan sebuah nilai. Berdasarkan nilai tersebut, keluarkan kategori nilai sebagai berikut: A untuk nilai 80-100, B untuk nilai 60-79, C untuk nilai 40-59, dan D untuk nilai di bawah 40.


"""

nilai = float(input('masukan nilai: '))

if nilai >= 80: #kondisi
  print('A') #statement
elif 79 >= nilai >= 60: #tambahan kondisi
  print('B')
elif 59 >= nilai >= 40: #tambahan kondisi
  print('C')
else: #kondisi jika diatas salah
  print('D')

"""# Soal 4

> Sistem Penilaian Mahasiswa Berbasis Robot

Buatlah sebuah program yang menghitung nilai akhir mahasiswa berdasarkan beberapa komponen penilaian: kehadiran (10%), tugas (20%), kuis (20%), UTS (25%), dan UAS (25%). Program harus meminta pengguna untuk memasukkan nilai untuk setiap komponen, kemudian menghitung dan menampilkan nilai akhir beserta predikat kelulusannya. Predikat kelulusan diberikan sebagai berikut:



A untuk nilai >= 80

B untuk nilai >= 70 dan < 80

C untuk nilai >= 60 dan < 70

D untuk nilai >= 50 dan < 60

E untuk nilai < 50


"""

kehadiran = float(input('nilai kehadiran: '))
tugas = float(input('nilai tugas: '))
kuis = float(input('nilai kuis: '))
uts = float(input('nilai UTS: '))
uas = float(input('nilai UAS: '))

nilai = (10/100 * kehadiran)+(20/100 * tugas)+(20/100 * kuis)+(25/100 * uts)+(25/100 * uas)
print('total keseluruhan nilai : ', nilai)

if nilai >= 80:
  print('A')
elif nilai >= 70 and nilai < 80:
  print('B')
elif nilai >= 60 and nilai < 70:
  print('C')
elif nilai >= 50 and nilai < 60:
  print('D')
else:
  print('E')

"""# Soal 5

> Menentukan Tahun Kabisat

Buatlah sebuah program yang menentukan apakah sebuah tahun adalah tahun kabisat. Sebuah tahun dianggap kabisat jika tahun tersebut habis dibagi 4 dan tidak habis dibagi 100, kecuali jika tahun tersebut habis dibagi 400.


"""

tahun = int(input("Masukkan tahun: "))

if (tahun % 4 == 0 and tahun % 100 != 0) or (tahun % 400 == 0):
    print(tahun, "adalah tahun kabisat")
else:
    print(tahun, "bukan tahun kabisat")